### PR TITLE
First release work only with OsClass v 2.2 and up

### PR DESCRIPTION
**Pull request by keny10**
Here is my watchlist pluggin for OsClass 2.2 and up 
Include French language

### CODE REVIEW

**Comment by juanramon** [comment]
Created a new branch called watchlist in osclass-plugins: https://github.com/osclass/osclass-plugins/tree/watchlist

**Comment by keny10** [comment]
Thanks i apreciate it.

Can you confirm me that you receive ads4osc pluggin change as today ? I am not sure if everything have been done right via gitgub this time.

**Comment by juanramon** [comment]
The last pull request is from two hours ago: https://github.com/osclass/osclass-plugins/pull/2 So I think that it has done correctly.

**Comment by keny10** [comment]
Ok thanks

**Pull request closed without merging**
